import { Recipe } from '@prisma/client'

const formatRecipeImages = (recipes: Recipe[]): Recipe[] => {
  return recipes.map((recipe): Recipe => {
    // @ts-ignore: weird error because relation typings are not generated by Prisma
    if (recipe.Image && recipe.Image.length) {
      // @ts-ignore: weird error because relation typings are not generated by Prisma
      return { ...recipe, images: recipe.Image, Image: [] } as Recipe
    }
    return recipe
  })
}

export { formatRecipeImages }
