import { Recipe } from '@prisma/client'

const formatRecipeImages = (recipes: Recipe[]): Recipe[] => {
    return recipes.map((recipe): Recipe => {
        let newRecipe: Recipe = { ...recipe }
        // @ts-ignore: weird error because relation typings are not generated by Prisma
        if (newRecipe.Image && newRecipe.Image.length) {
            // @ts-ignore: weird error because relation typings are not generated by Prisma
            newRecipe = { ...newRecipe, images: newRecipe.Image }
            // @ts-ignore: weird error because relation typings are not generated by Prisma
            delete newRecipe.Image
        }

        // @ts-ignore: weird error because relation typings are not generated by Prisma
        if (newRecipe.RecipeIngredient && newRecipe.RecipeIngredient.length) {
            // @ts-ignore: weird error because relation typings are not generated by Prisma
            newRecipe = {
                ...newRecipe,
                // @ts-ignore: weird error because relation typings are not generated by Prisma
                ingredients: newRecipe.RecipeIngredient.map((ingredient) => {
                    const withImages = {
                        ...ingredient,
                        ...ingredient.ingredient,
                        id: ingredient.id,
                        unit: ingredient.unit,
                    }
                    delete withImages.ingredient
                    return withImages
                }),
            }
            // @ts-ignore: weird error because relation typings are not generated by Prisma
            delete newRecipe.RecipeIngredient
        }
        // @ts-ignore: weird error because relation typings are not generated by Prisma
        if (newRecipe && (newRecipe.images || newRecipe.ingredients)) return newRecipe

        // @ts-ignore: weird error because relation typings are not generated by Prisma
        delete newRecipe.Image
        // @ts-ignore: weird error because relation typings are not generated by Prisma
        delete newRecipe.RecipeIngredient
        // @ts-ignore: weird error because relation typings are not generated by Prisma
        return { ...newRecipe, images: [], ingredients: [] }
    })
}

export default formatRecipeImages
