import { Recipe } from '@prisma/client'

const formatRecipeImages = (recipes: Recipe[]): Recipe[] => {
  return recipes.map((recipe): Recipe => {
    let newRecipe: Recipe = { ...recipe }
    // @ts-ignore: weird error because relation typings are not generated by Prisma
    if (newRecipe.Image && newRecipe.Image.length) {
      // @ts-ignore: weird error because relation typings are not generated by Prisma
      newRecipe = { ...newRecipe, images: newRecipe.Image }
      // @ts-ignore: weird error because relation typings are not generated by Prisma
      delete newRecipe.Image
    }

    // @ts-ignore: weird error because relation typings are not generated by Prisma
    if (newRecipe.RecipeIngredients && newRecipe.RecipeIngredients.length) {
      // @ts-ignore: weird error because relation typings are not generated by Prisma
      newRecipe = { ...newRecipe, ingredients: newRecipe.RecipeIngredients }
      // @ts-ignore: weird error because relation typings are not generated by Prisma
      delete newRecipe.RecipeIngredients
    }
    // @ts-ignore: weird error because relation typings are not generated by Prisma
    if (newRecipe && (newRecipe.images || newRecipe.ingredients)) return newRecipe

    // @ts-ignore: weird error because relation typings are not generated by Prisma
    delete newRecipe.Image
    // @ts-ignore: weird error because relation typings are not generated by Prisma
    delete newRecipe.RecipeIngredients
    // @ts-ignore: weird error because relation typings are not generated by Prisma
    return { ...newRecipe, images: [], ingredients: [] }
  })
}

export default formatRecipeImages
